### ISSUE TITLE
fatal: '$GIT_DIR' too big

### ISSUE THREAD

**Issue by AkumaRRR** [0xf4b1/bsod-kernel-fuzzing#1]
git clone --recursive https://github.com/0xf4b1/bsod-kernel-fuzzing.git

fails with a lot of 
fatal: '$GIT_DIR' too big

ps. I have both 
- core.longpaths true
- LongPathsEnabled = 1

**Comment by ma5d** [comment]
如果我的路径不方便改短怎么办
